program: train.py
name: sweep_crowdmod_ddpm_2D
method: random
metric:
  goal: minimize
  name: loss_2D
parameters:
  learning_rate:
    min: 0.00001
    max: 0.001
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [400, 600, 800]
  #optimizer:
  #  values: ["adam", "sgd"]